server:
  port: 8080

spring:
  # --- [NOVO] CONFIGURAÇÃO DE SEGURANÇA OIDC (KEYCLOAK) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          # Ela diz ao Gateway qual "emissor" de token ele deve confiar.
          issuer-uri: http://host.docker.internal:8180/realms/radares-realm
          # Aponta para o seu servidor Keycloak.
          jwk-set-uri: http://host.docker.internal:8180/realms/radares-realm/protocol/openid-connect/certs
  
  # --- CONFIGURAÇÃO DO GATEWAY ---
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      default-filters:
        # Remove cabeçalhos duplicados mantendo apenas o primeiro (do Gateway)
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      routes:
        - id: bff_route
          uri: lb://MICROSERVICO-RADARES-BFF
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3009"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  # [NOVO] Adiciona logs de debug para roteamento e service discovery
  logging:
    level:
      # Mostra detalhes de roteamento do gateway
      org.springframework.cloud.gateway: DEBUG
      # Mostra detalhes de descoberta de serviço (LoadBalancer)
      org.springframework.cloud.loadbalancer: TRACE