server:
  port: 8080

spring:
  # --- [NOVO] CONFIGURAÇÃO DE SEGURANÇA OIDC (KEYCLOAK) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          # Ela diz ao Gateway qual "emissor" de token ele deve confiar.
          issuer-uri: http://host.docker.internal:8180/realms/radares-realm
          # Aponta para o seu servidor Keycloak.
          jwk-set-uri: http://host.docker.internal:8180/realms/radares-realm/protocol/openid-connect/certs
  
  # --- CONFIGURAÇÃO DO GATEWAY ---
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: bff_route
          uri: lb://microservico-radares-bff
          predicates:
            - Path=/api/**
          filters:
            - PreserveHostHeader
      
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  # [NOVO] Adiciona logs de debug para roteamento e service discovery
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.security: DEBUG
      org.springframework.security.web.server: TRACE
      org.springframework.security.oauth2: TRACE
      org.springframework.cloud.loadbalancer: TRACE