server:
  port: 8080

spring:
  # --- [NOVO] CONFIGURAÇÃO DE SEGURANÇA OIDC (KEYCLOAK) ---
  security:
    oauth2:
      resourceserver:
        jwt:
          # Aponta para o seu servidor Keycloak.
          issuer-uri: http://keycloak:8080/realms/radares-realm
  
  # --- CONFIGURAÇÃO DO GATEWAY ---
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        - id: bff_route
          uri: lb://microservico-radares-bff
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
      
      globalcors:
        cors-configurations:
          '[/**]': # Aplica a todas as rotas
            allowedOrigins: "http://localhost:3009"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true