server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.6:8180/realms/radares-realm
          jwk-set-uri: http://192.168.0.6:8180/realms/radares-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 40s
      discovery:
        locator:
          enabled: true

      # Configuração Global de CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*" # Em prod, idealmente use a URL do front ex: "http://localhost:3009"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # ---------------------------------------------------------
        # ROTA UNIFICADA PARA WEBSOCKET (SockJS + STOMP)
        # ---------------------------------------------------------
        # Esta rota captura tanto o handshake HTTP (/info) quanto o upgrade WS
        - id: bff_websocket
          uri: lb:ws://microservico-radares-bff
          predicates:
            - Path=/api/ws/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            # Remove duplicatas se o BFF também enviar CORS
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST

        # ---------------------------------------------------------
        # ROTA HTTP REST PADRÃO
        # ---------------------------------------------------------
        - id: bff_route_api
          uri: lb://microservico-radares-bff
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.security: TRACE
      org.springframework.security.web.server: TRACE
      org.springframework.security.oauth2: TRACE
      org.springframework.cloud.loadbalancer: TRACE

  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always
    server:
      port: 8080