server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: microservice-radar-cart

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/cart_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostGISDialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutos (em milissegundos)
      cache-null-values: false # Não cacheia se o retorno for null
rabbitmq:
  exchange:
    name: radares_exchange
  routing:
    key: radares.cart